### ISSUE TITLE
Nothing Appeares

### ISSUE THREAD

**Issue by seikosantana** [xsoameix/openlf2#1]
Hi, I'm new to GitHub and the C language.

I downloaded whole files in a zip, and extracted it. I ran the openlf2.exe but no window or anything was shown. Are there anything I missed?

Thanks in advance!

**Comment by xsoameix** [comment]
The openlf2.exe should be placed in normal LF2 folder, then you can launch it without problem.

Thanks for your feedback.

**Comment by seikosantana** [comment]
Hmm.. I placed the openlf2.exe on my root directory of LF2 as shown.
<a href="https://imgur.com/4VFUajb"><img src="https://i.imgur.com/4VFUajb.png" title="source: imgur.com" /></a>
But that doesn't work. I also tried to run it as administrator but it does not change anything. Are there any runtimes I need to run this?

**Comment by xsoameix** [comment]
What the version of LF2 did you use? The openlf2.exe should be placed in latest version (2.0a) LF2 folder.

**Comment by xsoameix** [comment]
_openlf2.exe_ requires _openlf2.dll_. You should build this project to generate _openlf2.dll_, and place it into the LF2 directory.

**Comment by xsoameix** [comment]
openlf2.exe requires openlf2.dll. You should build this project to generate openlf2.dll, and place it into the LF2 directory. For more details, please see the section 2.1 in this [page](https://www.lf-empire.de/forum/showthread.php?tid=9369).

**Comment by seikosantana** [comment]
Can I get the dll somewhere, without having to build them?

**Comment by xsoameix** [comment]
I can build them and give you the generated dll, but why do you do that? The generated dll became useful only after you modified it. The original dll has same functionality in playing with the original LF2, you would feel no difference when playing.

**Comment by seikosantana** [comment]
I really want to test this. The reverse-engineering  is really unique for me.
Anyway, I am planning to recompile the game for Android platform, if possible. Unfortunately I am very inexperienced in this.

**Comment by xsoameix** [comment]
This is the [openlf2.dll](https://drive.google.com/file/d/1hATnYeA7Gye1o5Gy2ZP9jUMGX8Vyjbun/view?usp=sharing), and I hope that it will help you. If you have any questions, please feel free to ask.
