### ISSUE TITLE
Project File

### ISSUE THREAD

**Issue by seikosantana** [xsoameix/openlf2#2]
Hi,

Are there a project file for this? How can I edit the source or recompile it? What do I need to open them? Sorry if the questions are silly but I'm still new to programming..

**Comment by xsoameix** [comment]
This project use CMake to generate project file, you need to install it first.

CMake is cross-platform tool, so the command to generate project file would be little different for the platform you use.

Currently the CMakeLists.txt I wrote only support Linux platform, you can install Linux and follow the instructions in this [page](https://www.lf-empire.de/forum/showthread.php?tid=9369), or you can edit the _CMakeLists.txt_ to suit the tools you use, which may be Visual Studio, Cygwin, Codeblocks, or other tools.
